# Site settings
title: Unknown Entity's Blog
description: >
  Hi! I am a budding AI engineer and am working to improve my programming and problem solving. Mathematics is my field of interest.
  I enjoy learning about new algorithms, model architectures, and the working of the system. 
  My goal is to create write better software that helps people and invent free energy ;P
  I spend my free time checking out video games and movies. So feel free to tell me your fav games, stories and abt your work! 
  Always happy to make something useful. Open to project collabs!

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://unknown-entity98.github.io" # the base hostname & protocol for your site

author:
  fullname: Sameer
  googleplus: https://www.google.com/+SameerNavuduri
  github: unknown-entity98
  twitter: BB3898656085991
  # disqus: your_disqus_forum_shortname

# google_analytics: 'UA-XXXXXXXX-X'

# Syntax highlighting
# highlightstyle: ''
#styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
